# Study room

## Layer Norm for 1d data

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


In [2]:
features = torch.randn(2, 3)

In [3]:
features

tensor([[-0.3726,  0.5572,  0.0804],
        [-1.3519, -0.9464,  1.0852]])

In [5]:
layer_norm = nn.LayerNorm(3)

In [6]:
layer_norm(features)

tensor([[-1.2141,  1.2350, -0.0210],
        [-0.8887, -0.5084,  1.3971]], grad_fn=<NativeLayerNormBackward>)

In [9]:
batch_norm = nn.BatchNorm1d(3)

In [10]:
batch_norm(features)

tensor([[ 1.0000,  1.0000, -1.0000],
        [-1.0000, -1.0000,  1.0000]], grad_fn=<NativeBatchNormBackward>)